<?php

namespace Bekambeyene\Telebirr;

class ApplyFabricToken
{
    public $BASE_URL;
    public $fabricAppId;
    public $appSecret;
    public $merchantAppId;

    public function __construct($BASE_URL, $fabricAppId, $appSecret, $merchantAppId)
    {
        $this->BASE_URL = $BASE_URL;
        $this->fabricAppId = $fabricAppId;
        $this->appSecret = $appSecret;
        $this->merchantAppId = $merchantAppId;
    }

    /**
     * @Purpose: Apply fabric token generated by et-server
     *
     * @Param: no parameters needed it takes the fabricAppId and the appSecret from the constructor of class ApplyFabricToken
     * @Return: authToken
     */
    public function applyFabricToken()
    {
        $ch = curl_init();

        $headers = array(
            "Content-Type: application/json",
            "X-APP-Key: " . $this->fabricAppId
        );

        curl_setopt($ch, CURLOPT_URL, rtrim($this->BASE_URL, '/') . "/payment/v1/token");
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_HEADER, 0);

        $payload = array(
            "appSecret" => $this->appSecret
        );

        $data = json_encode($payload);

        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');
        curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, FALSE); // for dev environment only
        curl_setopt($ch, CURLOPT_TIMEOUT, 30);

        $authToken = curl_exec($ch);
        curl_close($ch);

        return $authToken;
    }
}
