name: Code Quality & Testing

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2, 8.3]
        laravel: [10.*, 11.*, 12.*, 13.*]

    name: P-${{ matrix.php }} - L-${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, openssl
          coverage: none

      - name: Install dependencies and Larastan dynamically
        run: |
          case "${{ matrix.laravel }}" in
            10.*)
              composer require --dev "larastan/larastan:^2.0" --no-update
              ;;
            *)
              composer require --dev "larastan/larastan:^3.0" "illuminate/testing" --no-update
              ;;
          esac
          composer update --prefer-dist --no-interaction --with-all-dependencies

      - name: Execute Static Analysis (PHPStan)
        run: |
          chmod +x vendor/bin/phpstan
          vendor/bin/phpstan analyse

      - name: Run Tests
        run: |
          chmod +x vendor/bin/phpunit
          vendor/bin/phpunit
